### ISSUE TITLE
modele kanapka, składnik, alergeny, grupa produktu

### ISSUE THREAD

**Issue by MarcinNowacki** [ork-a/pan_kanapka#2]
[Modele: kanapka, składnik, alergeny, grupa produktu](https://github.com/ork-a/pan_kanapka/pull/7)

**Comment by magdacwiklinska** [comment]
Poproszę o review

**Comment by MarcinNowacki** [comment]
Hej, poniżej to, co wg być może wymaga zmiany/przemyślenia. Niestety moje doświadczenia z python/django/bazy są niewielkie i mogę się mylić, nie znaleźć wszystkiego i ogólnie napisać jakieś głupoty, więc w razie czego wybaczcie ;)
1. proponuje nazywać modele w liczbie pojedynczej (Alergen, Składnik,...) - wydaje mi się, że teraz myślimy o modelach jako o tabelach (wtedy liczba mnoga pasuje), ale później w kodzie będą te modele funkcjonowały raczej jako "pojedyncze" obiekty.
3. w modelu Alergeny brakuje pola 'Ale_Nazwa'
4. być może dla ikon (Ale_Ikona, Skl_Ikona, Kan_Ikona, ... ) lepiej użyć typu ImageField zamiast BinaryField
5. dla pól Skl_Archiwalny i Kan_Archiwalny użyłbym typu BooleanField
6. dla pól przechowujących ceny (Skl_Cena, Kan_Cena) proponuję użyć DecimalField zamiast (IntegerField i FloatField)
7. Literówka: zamiast KaS_Ikona powinnno być chyba Kan_Ikona
8. Zamiast definiować model SkladnikiAlergeny może dałoby się użyć  pola "ManyToManyField" w modelu Skladniki.
9. w modelu KanapkiSkladniki jest jakby niespójny prefiks dla pól (Kas i KaS)
10. w modelu KanapkiSkladniki pole Kas_Ilosc jest zdefiniowane dwa razy 
11. Jesli w modelu skladniki mamy pole Skl_GramNaPorcje, to w modelu KanapkiSkladniki trzeba sie zastanowić co będzie oznaczac Kas_Ilosc, i doprecyzowac nazwę, np. Kas_IloscPorcjiNaKanapkę. Albo (może lepiej) zrezygnować z pola Skl_GramNaPorcje, i doprecyzować Kas_Ilosc jako Kas_IloscGramWKanapce (pewnie wtedy tez zmienić Skl_Kcal na Skl_KcalNaStoGram)
12. Jako kluczy głównych można by może użyć AutoField(primary_key=True), z tego co przeczytałem, numer będzie się wtedy nadawał automatycznie.

**Comment by magdacwiklinska** [comment]
> 
> 
> Hej, poniżej to, co wg być może wymaga zmiany/przemyślenia. Niestety moje doświadczenia z python/django/bazy są niewielkie i mogę się mylić, nie znaleźć wszystkiego i ogólnie napisać jakieś głupoty, więc w razie czego wybaczcie ;)
> 
>     1. proponuje nazywać modele w liczbie pojedynczej (Alergen, Składnik,...) - wydaje mi się, że teraz myślimy o modelach jako o tabelach (wtedy liczba mnoga pasuje), ale później w kodzie będą te modele funkcjonowały raczej jako "pojedyncze" obiekty.
**nazwnictwo, to nieduzy problem, nie ma problemu, przedyskutujemy w szerszym gronie** 
>     2. w modelu Alergeny brakuje pola 'Ale_Nazwa'
**u mnie jest, nie było u Tomka**
>     3. być może dla ikon (Ale_Ikona, Skl_Ikona, Kan_Ikona, ... ) lepiej użyć typu ImageField zamiast BinaryField
**zdecydowalismy sie uzywac bazy danych w sqlite, w ktorym ustnieye tylko typ BLOB, dlatego cokolwiek innego zrobimy w Djangobedzie przetlumaczone w SQLite na typ BLOB**
>     4. dla pól Skl_Archiwalny i Kan_Archiwalny użyłbym typu BooleanField
>     5. dla pól przechowujących ceny (Skl_Cena, Kan_Cena) proponuję użyć DecimalField zamiast (IntegerField i FloatField)
**w SQLite istnieje tylko typ REAL i INTEGER, wiec czegokolwiek uzyjemy w Django, bedzie przekonwertowane na typ REAL i INTEGER - https://www.sqlite.org/datatype3.html**
>     6. Literówka: zamiast KaS_Ikona powinnno być chyba Kan_Ikona
**ok racja, poprawione w osobnym "commicie"**
>     7. Zamiast definiować model SkladnikiAlergeny może dałoby się użyć  pola "ManyToManyField" w modelu Skladniki.
**tak jak jest teraz powoduje, ze baza danych jest znormalizowana zgodnie ze standardami stopnia (1/2/3), a jesli bedzie inaczej, to bedzie wbrew zasadom normalizacji bazy danych**
>     8. w modelu KanapkiSkladniki jest jakby niespójny prefiks dla pól (Kas i KaS)
ok racja, poprawione w osobnym "commicie"**
>     9. w modelu KanapkiSkladniki pole Kas_Ilosc jest zdefiniowane dwa razy
**ok racja, poprawione w osobnym "commicie"**
>     10. Jesli w modelu skladniki mamy pole Skl_GramNaPorcje, to w modelu KanapkiSkladniki trzeba sie zastanowić co będzie oznaczac Kas_Ilosc, i doprecyzowac nazwę, np. Kas_IloscPorcjiNaKanapkę. Albo (może lepiej) zrezygnować z pola Skl_GramNaPorcje, i doprecyzować Kas_Ilosc jako Kas_IloscGramWKanapce (pewnie wtedy tez zmienić Skl_Kcal na Skl_KcalNaStoGram)
> 
>     11. Jako kluczy głównych można by może użyć AutoField(primary_key=True), z tego co przeczytałem, numer będzie się wtedy nadawał automatycznie.
**nie ma już tego pola w moim modelu bo na wniosek Oli i jej review zostało zamienione na domyślne generowane przez django**

**dzięki Marcin na super review. Dopiero teraz widzę ile zrobiłam błędów i wszystko powyłapywałeś. Dodałam kolejnego commita do mojego "merge requesta" z implementacją opisanych wyżej uwag.**

**Comment by PanBulka** [comment]
@magdacwiklinska @MarcinNowacki @ork-a, kawał świetnej roboty - możemy zmienić BinaryField na ImageField i dogadać jakoś strukturę/nazewnictwo w projekcie?  Przygarnę zmianę pól w modelu (chyba, że źle myślę, to mnie poprawcie), ale wydaje mi się, że zanim coś wypchnę do brancha musimy dogadać jedno wspólne stanowisko gdzie i jak :)
